In [197]:
import pandas as pd
import numpy as np
import random

# Dataset

In [198]:
dataset=pd.read_csv('/home/root123/Documents/semester-3/Data mining/codes/kmedoids/kmedoids.csv')

In [199]:
matrix=np.matrix(dataset.T)

In [200]:
matrix

matrix([[2, 6],
        [3, 4],
        [3, 8],
        [5, 7],
        [6, 2],
        [6, 4],
        [7, 3],
        [7, 4],
        [8, 5],
        [7, 6]])

# Distance matrix

In [205]:
def dist_mat(numof_k):
    distance_matrix_old= np.zeros((matrix.shape[0],numof_k))
    k = np.random.randint(matrix.shape[0], size=numof_k)
    for i in range(len(k)):
        for j in range(matrix.shape[0]):
            distance_matrix_old[j,i] = np.sum(abs(matrix[j,0:]-matrix[k[i],:]))
    return(distance_matrix_old)

In [206]:
x=dist_mat(3)
x

array([[5., 6., 7.],
       [6., 3., 6.],
       [6., 7., 8.],
       [3., 4., 5.],
       [5., 2., 5.],
       [3., 0., 3.],
       [3., 2., 3.],
       [2., 1., 2.],
       [2., 3., 0.],
       [0., 3., 2.]])

In [207]:
def clusters(dist_mat):
    minimum=[]
    clust=[]
    for i in range(dist_mat.shape[1]):
         clust.append([])
    for i in range(dist_mat.shape[0]):
        for j in range(dist_mat.shape[1]):
            if min(dist_mat[i])==dist_mat[i,j]:
                minimum.append(min(dist_mat[i]))
                clust[j].append(dist_mat[i])
    return(clust,minimum)

In [208]:
old_min_value=cluster(x)[1]

# k-medoids

In [211]:
def kmedoids(numof_k,n):
    distance_matrix_new= np.zeros((matrix.shape[0],numof_k))
    k = np.random.randint(matrix.shape[0], size=numof_k)
    list2=[i for i in range(matrix.shape[0]) if i not in k]
    for iteration in range(n):
        for i in range(len(k)):
            for j in range(len(list2)):
                k[i]=list2[j]
                for k_val in range(len(k)):
                    for value in range(10):
                        distance_matrix_new[value,k_val] = np.sum(abs(matrix[value,0:]-matrix[k[k_val],:]))
                        new_min_value=clusters(distance_matrix_new)[1]
                        if sum(new_min_value)- sum(old_min_value)<0:
                            cluster=clusters(distance_matrix_new)[0]
                        else:
                            cluster=clusters(x)[0]
    return(cluster)

In [212]:
kmedoids(3,10)

[[array([5., 6., 7.]),
  array([6., 7., 8.]),
  array([3., 4., 5.]),
  array([0., 3., 2.])],
 [array([6., 3., 6.]),
  array([5., 2., 5.]),
  array([3., 0., 3.]),
  array([3., 2., 3.]),
  array([2., 1., 2.])],
 [array([2., 3., 0.])]]